var keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({
	ANSWER_ADD: null,
	ANSWER_REMOVE: null,
	ANSWER_SHIFT_UP: null,
	ANSWER_SHIFT_DOWN: null,
	ANSWER_ADD_CONDITION: null,
	ANSWER_REMOVE_CONDITION: null,
	ANSWER_CHANGE_CONDITION: null,
	ANSWER_ADD_CONDITIONTEXT: null,
	ANSWER_REMOVE_CONDITIONTEXT: null,
	ANSWER_CHANGE_CONDITIONTEXT: null,
	ANSWER_ADD_CONFORMITY: null,
	ANSWER_REMOVE_CONFORMITY: null,
	ANSWER_CHANGE_CONFORMITY: null,
	ANSWER_CHANGE_SIZE: null,
	ANSWER_SELECTED: null,
	ANSWER_CHANGE_TEXT: null,
	ANSWER_CHANGE_WEIGHT: null
});