var keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({
	RECEIVE_QUESTION_DATA: null,
	RECEIVE_STRUCTURE_DATA: null,
	SAVE_QUESTION_DATA: null,

	UPLOADED_ANSWER_IMAGE: null,
	UPLOADED_ANSWER_ERROR_IMAGE: null,
	REMOVE_ANSWER_IMAGE: null,
	REMOVE_ANSWER_ERROR_IMAGE: null,

	UPLOADED_QUESTION_IMAGE: null,
	UPLOADED_QUESTION_ERROR_IMAGE: null,
	REMOVE_QUESTION_IMAGE: null,
	REMOVE_QUESTION_ERROR_IMAGE: null
});