var keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({
	RECEIVE_SETTINGS_DATA: null,
	CHANGE_TITLE: null,
	CHANGE_PASSING_SCORE: null,
	CHANGE_DURATION_MINUTES: null,
	CHANGE_DURATION_DAYS: null,
	CHANGE_ATTEMPTS_COUNT: null,
	CHANGE_STATUS: null,
	CHANGE_NOT_SENT_CORRECT_ANSWER: null,
	CHANGE_DISPLAY_RESULT: null,
	CHANGE_NOT_DISPLAY_LAST_ATTEMPT: null,
	CHANGE_NOT_DISPLAY_FEEDBACK: null,
	CHANGE_DISPLAY_RESULT_REPORT: null,
	CHANGE_DISPLAY_ANSWERS_IN_REPORT: null,
	CHANGE_DISPLAY_CORRECT_ANSWER_IN_REPORT: null,
	CHANGE_NOT_DISPLAY_UNFINISHED_SCORE: null
});