var keyMirror = require('keyMirror');

module.exports = keyMirror({
	RECEIVE_STRUCTURE_DATA: null,
	SAVE_STRUCTURE_DATA: null,
	SAVE_SECTION: null,
	REPLACE_SECTION: null,
	REMOVE_SECTION: null,
	SHIFT_UP_SECTION: null,
	SHIFT_DOWN_SECTION: null,
	TOGGLE_EXPAND_SECTION: null,
	TOGGLE_EXPAND_SECTIONS: null,
	REMOVE_QUESTION: null,
	REPLACE_QUESTION_IN_SECTION: null,
	REPLACE_QUESTION_IN_NEW_SECTION: null,
	SHIFT_UP_QUESTION: null,
	SHIFT_DOWN_QUESTION: null
});